  local_costmap:
    global_frame: odom
    robot_base_frame: base_link

    update_frequency: 10.0
    publish_frequency: 10.0
    transform_tolerance: 0.5  

    rolling_window: true
    width: 6
    height: 6
    resolution: 0.05
    inflation_layer:
      inflation_radius: 0.3  # 减小膨胀半径，减少避障范围（默认约 0.5）